Controllers films users
Kadyke/java-filmorate pull request #4
Opened 2023-03-11 17:35 UTC by Kadyke

У меня почему-то после второго комита не пошли тесты, как в первый раз, но в постмане все проходят.

2023-03-11 19:08 UTC, db-exp requested changes

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film) throws ValidationException {
В pom есть spring-validation - его тут самое то использовать через аннотацию Valid

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@RequestBody Film film) throws ValidationException {
В pom есть spring-validation - его тут самое то использовать через аннотацию Valid

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody User user) throws ValidationException {
тут тоже хорошо бы Valid использовать

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User updateUser(@RequestBody User user) throws ValidationException {
тут тоже хорошо бы Valid использовать

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
тут для того, чтобы работал spring-validation нужно добавить
Size/NotBlank для String 
NonNull для даты итд

2023-03-11 19:08 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
тут для того, чтобы работал spring-validation нужно добавить
Size/NotBlank для String 
Past для даты итд

2023-03-12 04:20 UTC, Kadyke commented
Не нашел только как можно сделать проверку - должно быть не позже определенной даты.

2023-03-12 11:01 UTC, db-exp approved these changes

2023-03-12 11:42 UTC, merged