feat: добавить базы данных
Kadyke/java-filmorate pull request #7
Opened 2023-04-05 12:06 UTC by Kadyke

это тз сформулировано хуже всего

2023-04-05 20:32 UTC, db-exp requested changes

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        SqlRowSet selectId = jdbcTemplate.queryForRowSet("SELECT id FROM films ORDER BY id DESC;");
Посмотри в сторону https://www.baeldung.com/spring-jdbc-autogenerated-keys
Потому что такой select следующего id в реальном многопоточном приложении работать не будет - уже при нескольких параллельных запросах будет "гонка"

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                Film film = new Film(
и тут

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            SqlRowSet selectGenres = jdbcTemplate.queryForRowSet("SELECT * FROM genres WHERE id IN (SELECT genre_id " +
повторяется в методах

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            SqlRowSet selectNameOfMpa = jdbcTemplate.queryForRowSet("SELECT name FROM Mpa WHERE id = ?;",
getMpa можно использовать

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        SqlRowSet selectId = jdbcTemplate.queryForRowSet("SELECT id FROM users ORDER BY id DESC;");
как и для фильмов - нужно поправить работу с id

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        SqlRowSet selectUser = jdbcTemplate.queryForRowSet("SELECT * FROM users WHERE id = ?;", id);
лучше вынести в отдельный метод - ниже дублируется в каждом методе

2023-04-05 20:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            jdbcTemplate.update("DELETE FROM users WHERE id = ?;", id);
тогда нужно и из друзей у других его удалить

2023-04-06 12:15 UTC, Kadyke commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            jdbcTemplate.update("DELETE FROM films_in_genres WHERE film_id = ?;", film.getId());
тут удаляется не старая запись, а очищается список жанров по фильму

2023-04-07 07:02 UTC, Kadyke commented
Спасибо за ссылки, было интересно реализовать новый функционал по валидации и получению айди

2023-04-07 12:41 UTC, db-exp requested changes

2023-04-07 12:41 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends Exception {
давай сделаем наследование от RuntimeException,  чтобы везде throws не писать
Кастомные ошибки обычно от Exception не делают

2023-04-08 07:13 UTC, db-exp requested changes

2023-04-08 07:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                } catch (Exception ignored) {
игнорить - очень плохой паттерн, давай лучше бросать как раз кастомную ошибку

2023-04-08 07:36 UTC, Kadyke commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                } catch (Exception ignored) {
а какую кастомную ошибку то кидать? в тестах кидают дублирующий жанр "genres": [{ "id": 1}, { "id": 2}, { "id": 1}], чтобы таблица не мусорилась, я сделал сочетание значений уникальным ключом, соответственно, если кинуть дубль возникает sql-исключение, но согласно логике тестов, то не является bad_request, соответственно дублирующие значение просто игнорируется. Или мусорить таблицу дублями более хорошее решение?

2023-04-08 08:11 UTC, Kadyke commented
хотя нашел в решение в обработке на уровне коллекции

2023-04-08 19:33 UTC, db-exp approved these changes

2023-04-09 08:12 UTC, merged